---
name: Lint

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  read-all

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: read
      statuses: write
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0

      - name: Lint Codebase
        uses: super-linter/super-linter/slim@4ce20838b8ab83717e78138c5b3a1407148e0918 # v8.7.0
        env:
          DEFAULT_BRANCH: origin/main
          VALIDATE_ALL_CODEBASE: true
          VALIDATE_CSS: true
          VALIDATE_GITLEAKS: true
          VALIDATE_GITHUB_ACTIONS: true
          VALIDATE_HTML: true
          VALIDATE_MARKDOWN: true
          VALIDATE_YAML: true
          VALIDATE_JAVASCRIPT_PRETTIER: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
