---
name: Security

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  semgrep:
    name: Analyze (Semgrep)
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      security-events: write
      actions: read
    container:
      image: semgrep/semgrep:1.161.0@sha256:326e5f41cc972bb423b764a14febbb62bbad29ee1c01820805d077dd868fea48
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Run Semgrep (report)
        run: semgrep scan --config auto --sarif --output semgrep.sarif || true
      - name: Run Semgrep (blocking)
        run: semgrep scan --config auto --error
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@7188fc363630916deb702c7fdcf4e481b751f97a # v4.37.1
        with:
          sarif_file: semgrep.sarif
        if: always()

  codeql:
    name: Analyze (CodeQL)
    runs-on: ubuntu-24.04
    permissions:
      security-events: write
      packages: read
      actions: read
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Initialize CodeQL
        uses: github/codeql-action/init@7188fc363630916deb702c7fdcf4e481b751f97a # v4.37.1
        with:
          languages: javascript-typescript
          build-mode: none
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@7188fc363630916deb702c7fdcf4e481b751f97a # v4.37.1
        with:
          category: "/language:javascript-typescript"
